export const COLORS = {
  LUNNHEIM_OLIVE: "#AA9966",
  LUNNHEIM_DARK_OLIVE: "#474224",
  LUNNHEIM_PALE_YELLOW: "#E9D1A0",
  LUNNHEIM_IVORY_YELLOW: "#FFF6DE",
  LUNNHEIM_VIBRANT_YELLOW: "#FFBE2E",
  LUNNHEIM_DUSTY_PINK: "#EFB9AB",
  LUNNHEIM_LIGHT_PINK: "#D9D9D9",
  LUNNHEIM_BLACK: "#000000",
  LUNNHEIM_WHITE: "#FFFFFF",
}
